# Extract Pixel Values at Points and Zonal Statistics on Polygons from Geokuup

This notebook demonstrates how to extract pixel values at given point locations and calculate zonal statistics for polygons from Cloud-Optimized-Geotiffs (COGs) stored in the Estonian Environmental Data Cube (Geokuup) using the SpatioTemporal Asset Catalog (STAC) API.

## Setup

Import required libraries for interacting with STAC API, handling COGs and geodataframes, and define functions for querying STAC items and extracting pixel values from queried STAC items.

In [1]:
!pip install pystac_client

Collecting pystac_client
  Downloading pystac_client-0.9.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: requests>=2.28.2 in /usr/local/lib/python3.12/dist-packages (from pystac_client) (2.32.4)
Collecting pystac>=1.10.0 (from pystac[validation]>=1.10.0->pystac_client)
  Downloading pystac-1.14.3-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pystac_client) (2.9.0.post0)
Requirement already satisfied: jsonschema~=4.18 in /usr/local/lib/python3.12/dist-packages (from pystac[validation]>=1.10.0->pystac_client) (4.26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pystac_client) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.2->pystac_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.2->pystac_client) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.2->pystac_client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.2->pystac_client) (2026.4.22)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac_client) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac_client) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac_client) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema~=4.18->pystac[validation]>=1.10.0->pystac_client) (0.30.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema~=4.18->pystac[validation]>=1.10.0->pystac_client) (4.15.0)
Downloading pystac_client-0.9.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 557.4 kB/s eta 0:00:00
Downloading pystac-1.14.3-py3-none-any.whl (208 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.5/208.5 kB 2.4 MB/s eta 0:00:00
Installing collected packages: pystac, pystac_client
Successfully installed pystac-1.14.3 pystac_client-0.9.0

In [1]:
# import libraries

import os
import time
import re
import io
import urllib.request
import tempfile
from IPython.display import display
import ipywidgets as widgets

import rasterio
import pandas as pd
import geopandas as gpd
from rasterstats import point_query, zonal_stats
import pystac_client

### Define functions

In [3]:
# define function for upload widget
def unpack_file(file_obj):
    # multiple cases for different widget version
    # case 1: tuple (name, dict)
    if isinstance(file_obj, tuple) and len(file_obj) == 2:
        name, meta = file_obj
        return name, meta.get("content")

    # case 2: dict with expected keys
    if isinstance(file_obj, dict):
        name = file_obj.get("name") or file_obj.get("metadata", {}).get("name")
        content = file_obj.get("content")
        if name is None:
            raise KeyError("Cannot find filename in dict")
        return name, content

    raise TypeError(f"Unsupported file format: {type(file_obj)}")

def upload_file(uploader):
    file = next(iter(uploader.value.values() if isinstance(uploader.value, dict) else uploader.value))

    name, content = unpack_file(file)
    name = name.lower()

    # GIS formats
    if name.endswith((".gpkg", ".shp", ".geojson", ".json")):
        tmp = tempfile.NamedTemporaryFile(suffix=name, delete=False)
        tmp.write(content)
        tmp.close()
        return gpd.read_file(tmp.name)

    raise ValueError(f"Unsupported file type: {name}")

def reset_uploader():
    global uploader
    try:
        uploader.close()
    except:
        pass

    uploader = widgets.FileUpload(
        accept=".gpkg,.shp,.geojson,.csv",
        multiple=False
    )
    return uploader

# define the function to convert date range into strings used in the column for extracted values
def extract_date_range(asset_href):
    """
    Extract YYMMDD_YYMMDD from asset filename.
    """

    filename = os.path.basename(asset_href)

    match = re.search(
        r"(\d{4}-\d{2}-\d{2})_(\d{4}-\d{2}-\d{2})",
        filename
    )

    if not match:
        return "nodate"

    start = match.group(1).replace("-", "")
    end = match.group(2).replace("-", "")

    return f"{start}-{end}"

# define the function for extracting raster values at points
def extract_point_values(
    catalog,
    points_gdf,
    collection,
    stats=("mean",),
    date_range=None,
    max_items=100
):
    """
    Extract raster point values from STAC COG assets.

    Parameters
    ----------
    catalog : pystac_client.Client
        Open STAC client

    points_gdf : GeoDataFrame
        Point geometries

    collection : str
        STAC collection ID

    stats : list or tuple
        Temporal composite assets to extract
        e.g. ("mean", "max", "median")

    date_range : str
        STAC datetime range
        e.g. "2023-06-01/2023-08-31"

    max_items : int
        Maximum number of STAC items

    Returns
    -------
    GeoDataFrame
        Original points with extracted raster values
    """

    # preserve original CRS
    gdf_native = points_gdf.copy().reset_index(drop=True)

    if gdf_native.crs is None:
        raise ValueError("Input GeoDataFrame has no CRS")

    gdf_native["point_id"] = gdf_native.index

    # ensure iterable
    if isinstance(stats, str):
        stats = [stats]

    # STAC search in EPSG:4326
    gdf_search = gdf_native.to_crs(epsg=4326)

    bbox = list(gdf_search.total_bounds)

    search = catalog.search(
        collections=[collection],
        bbox=bbox,
        datetime=date_range,
        max_items=max_items
    )

    items = list(search.items())

    print(f"Found {len(items)} items")

    # loop through items
    for item in items:

        for stat in stats:

            asset_key = f"ndvi_{stat}"

            asset = item.assets.get(asset_key)

            if not asset:
                print(f"Skipping {item.id}: missing {asset_key}")
                continue

            # skip non-data assets
            if asset.roles and "data" not in asset.roles:
                continue

            raster_url = asset.href

            # 4. match raster CRS
            with rasterio.open(raster_url) as src:
                raster_crs = src.crs

            gdf = gdf_native

            if gdf.crs != raster_crs:
                gdf = gdf.to_crs(raster_crs)

            # extract point values
            values = point_query(
                vectors=gdf,
                raster=raster_url,
                interpolate="nearest"
            )

            # column naming
            dt = extract_date_range(raster_url)

            col_name = f"{asset_key}_{dt}"

            gdf_native[col_name] = values

    return gdf_native

# define the function for extracting raster values at points
def extract_zonal_stats(
    catalog,
    polygons_gdf,
    collection,
    stats=("mean",),
    zonal_stat=("mean",),
    date_range=None,
    max_items=100
):
    """
    Extract zonal statistics from STAC COG assets.

    Parameters
    ----------
    catalog : pystac_client.Client
        Open STAC client

    polygons_gdf : GeoDataFrame
        Polygon geometries

    collection : str
        STAC collection ID

    stats : list or tuple
        Temporal composite assets to extract
        e.g. ("mean", "max", "median")

    zonal_stat : list or tuple
        Spatial statistics calculated by rasterstats
        e.g. ("mean", "median", "std")

    date_range : str
        STAC datetime range
        e.g. "2023-06-01/2023-08-31"

    max_items : int
        Maximum number of STAC items

    Returns
    -------
    GeoDataFrame
        Original polygons with zonal statistics
    """

    # preserve original CRS
    gdf_native = polygons_gdf.copy().reset_index(drop=True)

    if gdf_native.crs is None:
        raise ValueError("Input GeoDataFrame has no CRS")

    gdf_native["poly_id"] = gdf_native.index

    # ensure iterable
    if isinstance(stats, str):
        stats = [stats]

    if isinstance(zonal_stat, str):
        zonal_stat = [zonal_stat]

    # STAC search in EPSG:4326
    gdf_search = gdf_native.to_crs(epsg=4326)

    bbox = list(gdf_search.total_bounds)

    search = catalog.search(
        collections=[collection],
        bbox=bbox,
        datetime=date_range,
        max_items=max_items
    )

    items = list(search.items())

    print(f"Found {len(items)} items")

    # loop through items
    for item in items:

        for stat in stats:

            asset_key = f"ndvi_{stat}"

            asset = item.assets.get(asset_key)

            if not asset:
                print(f"Skipping {item.id}: missing {asset_key}")
                continue

            # skip non-data assets
            if asset.roles and "data" not in asset.roles:
                continue

            raster_url = asset.href

            # match raster CRS
            with rasterio.open(raster_url) as src:
                raster_crs = src.crs

            gdf = gdf_native

            if gdf.crs != raster_crs:
                gdf = gdf.to_crs(raster_crs)

            # calculate zonal statistics
            zs = zonal_stats(
                vectors=gdf.geometry,
                raster=raster_url,
                stats=list(zonal_stat)
            )

            # attach results
            dt = extract_date_range(raster_url)

            for zstat in zonal_stat:

                values = [z.get(zstat) for z in zs]

                col_name = f"{asset_key}_{dt}_zonal_{zstat}"

                gdf_native[col_name] = values

    return gdf_native

### Connect to the API

In [4]:
# Connect to the API

STAC_URL = "https://metadata.geokuup.ee/stac/api/v1/"

catalog = pystac_client.Client.open(STAC_URL)

print("Title      :", catalog.title)
print("Description:", catalog.description)

Title      : Geokuup STAC API
Description: SpatioTemporal Asset Catalog API for geospatial data discovery and access

### Browse available collections

In [5]:
# Browse available collections

print("Collections available:\n")
for collection in catalog.get_collections():
    extent = collection.extent.spatial.bboxes[0]
    print(f"  {collection.id}")
    print(f"    Title  : {collection.title}")
    print(f"    Extent : {extent}")
    print()

Collections available:

  estonia-soils-10m
    Title  : Estonia Soil Properties
    Extent : [21.664072, 57.471219, 28.275494, 59.831227]

  estonia-sentinel2-ndvi
    Title  : Estonia Sentinel-2 NDVI (2017-2025)
    Extent : [21.664072, 57.471219, 28.275494, 59.831227]

  estonia-topo-10m
    Title  : Estonia Topographic Variables 10 m
    Extent : [21.664072, 57.471219, 28.275494, 59.831227]

Inspect a collection (e.g. estonia-sentinel2-ndvi)

In [6]:
ndvi_collection = catalog.get_collection("estonia-sentinel2-ndvi")

print("Collection   :", ndvi_collection.id)
print("Title        :", ndvi_collection.title)
print("Description  :", ndvi_collection.description)
print()

# Spatial extent
bbox = ndvi_collection.extent.spatial.bboxes[0]
print(f"Spatial extent : {bbox}")

# Temporal extent
t = ndvi_collection.extent.temporal.intervals[0]
print(f"Temporal extent: {t[0]} → {t[1]}")

Collection   : estonia-sentinel2-ndvi
Title        : Estonia Sentinel-2 NDVI (2017-2025)
Description  : Normalized Difference Vegetation Index (NDVI) seasonal composites derived from Sentinel-2 imagery over Estonia. Three seasons per year: spring (April 1 - May 31), summer (June 1 - August 31), and autumn (September 1 - October 31). Composites include maximum, mean, median, minimum, range, and standard-deviation statistics per season.

Spatial extent : [21.664072, 57.471219, 28.275494, 59.831227]
Temporal extent: 2017-04-01 00:00:00+00:00 → 2025-10-31 23:59:59+00:00

## Example 1: Extract pixel values at points

#### Load point geometries

Read demo point layer from the Github repository

In [7]:
# define the URL to demo_point.gpkg
url = "https://raw.githubusercontent.com/LandscapeGeoinformatics/lgeo_datacube_pub/main/extract_indices_values/demo_point.gpkg"
urllib.request.urlretrieve(url, "demo_point.gpkg")

# alternatively, use !wget function to load the demo point from the Github repository (uncomment below)
#!wget raw.githubusercontent.com/LandscapeGeoinformatics/lgeo_datacube_pub/main/extract_indices_values/demo_point.gpkg

('demo_point.gpkg', <http.client.HTTPMessage at 0x1ee74df5f90>)

In [8]:
points_gdf = gpd.read_file("demo_point.gpkg")
points_gdf.head()

   id          type                        geometry
0   1  field island   POINT (632084.69 6553633.435)
1   2   arable land   POINT (632246.002 6553289.77)
2   3         water  POINT (629597.196 6549949.798)
3   4        forest  POINT (631217.084 6554656.593)
4   5      built-up  POINT (628624.995 6554793.371)

##### Using your own point layer

If using Colab, a point layer can be uploaded by running the cell below

In [9]:
from google.colab import files
uploaded = files.upload()

ModuleNotFoundError: No module named 'google.colab'

In [62]:
# read the uploaded file. Ensure matching filename.

points_gdf = gpd.read_file("demo_point.gpkg")

##### If running locally, run the cell below and use the button to select a point layer

In [10]:
upload = reset_uploader()
upload

FileUpload(value=(), accept='.gpkg,.shp,.geojson,.csv', description='Upload')

In [11]:
points_gdf = upload_file(upload)
points_gdf.head()

   id          type                        geometry
0   1  field island   POINT (632084.69 6553633.435)
1   2   arable land   POINT (632246.002 6553289.77)
2   3         water  POINT (629597.196 6549949.798)
3   4        forest  POINT (631217.084 6554656.593)
4   5      built-up  POINT (628624.995 6554793.371)

### Extract pixel values of Satellite image derivatives
Use the point locations to extract NDVI values from Sentinel-2 assets.

In [12]:
points_out = extract_point_values(
    catalog=catalog,
    points_gdf=points_gdf,
    collection="estonia-sentinel2-ndvi",
    stats=["mean", "median"],
    date_range="2018-04-01/2018-05-31"
)

Found 1 items

In [13]:
points_out.head()

,id,type,geometry,point_id,ndvi_mean_20180401-20180531,ndvi_median_20180401-20180531
0,1,field island,POINT (632084.69 6553633.435),0,426,403
1,2,arable land,POINT (632246.002 6553289.77),1,244,253
2,3,water,POINT (629597.196 6549949.798),2,-34,2
3,4,forest,POINT (631217.084 6554656.593),3,618,610
4,5,built-up,POINT (628624.995 6554793.371),4,150,144

### Export extracted values result
Save the queried raster values to GeoPackage and CSV.

In [14]:
# save points with extracted values as geopackage or csv

points_out.to_file("points_output.gpkg", driver="GPKG")
points_out.to_csv("points_output.csv", index=False)

## Example 3: Extract zonal statistics at areas

### Load polygon geometries

#### Read demo polygon layer from the Github repository

In [15]:
# define the URL to demo_point.gpkg
url = "https://raw.githubusercontent.com/LandscapeGeoinformatics/lgeo_datacube_pub/main/extract_indices_values/demo_area.gpkg"
urllib.request.urlretrieve(url, "demo_area.gpkg")

# alternatively, use !wget function to load the demo point from the Github repository (uncomment below)
#!wget https://github.com/LandscapeGeoinformatics/lgeo_datacube_pub/blob/main/extract_indices_values/demo_area.gpkg

('demo_area.gpkg', <http.client.HTTPMessage at 0x1ee46427f70>)

In [16]:
# read the uploaded polygon layer file. Ensure matching filename.

polygons_gdf = gpd.read_file("demo_area.gpkg")

#### Using your own point layer

In [71]:
from google.colab import files
uploaded = files.upload()

Saving demo_area.gpkg to demo_area (1).gpkg

In [17]:
# read the uploaded polygon layer file. Ensure matching filename.

polygons_gdf = gpd.read_file("demo_area.gpkg")

##### If running locally, run the cell below and use the button to select a polygon layer

In [18]:
upload = reset_uploader()
upload

FileUpload(value=(), accept='.gpkg,.shp,.geojson,.csv', description='Upload')

In [19]:
polygons_gdf = upload_file(upload)
polygons_gdf.head()

   id          type                                           geometry
0   1  field island  POLYGON ((632084.69 6553652.051, 632085.015 65...
1   2   arable land  POLYGON ((632246.002 6553308.387, 632246.327 6...
2   3         water  POLYGON ((629597.196 6549968.415, 629597.521 6...
3   4        forest  POLYGON ((631217.084 6554675.209, 631217.409 6...
4   5      built-up  POLYGON ((628624.995 6554811.988, 628625.32 65...

### Extract zonal statistics for satellite derivatives
Calculate zonal statistics for Sentinel-2 NDVI using median spatial aggregation.

In [20]:
polygons_out = extract_zonal_stats(
    catalog=catalog,
    polygons_gdf=polygons_gdf,
    collection="estonia-sentinel2-ndvi",
    stats=["max", "mean"],                  # indicates temporal composite asset
    zonal_stat="median",                    # indicates spatial aggregation method for zonal stats
    date_range="2018-04-01/2018-05-31"
)

Found 1 items

In [21]:
polygons_out.head()

,id,type,geometry,poly_id,ndvi_max_20180401-20180531_zonal_median,ndvi_mean_20180401-20180531_zonal_median
0,1,field island,"POLYGON ((632084.69 6553652.051, 632085.015 65...",0,750.5,402.0
1,2,arable land,"POLYGON ((632246.002 6553308.387, 632246.327 6...",1,383.0,244.0
2,3,water,"POLYGON ((629597.196 6549968.415, 629597.521 6...",2,272.5,-36.0
3,4,forest,"POLYGON ((631217.084 6554675.209, 631217.409 6...",3,930.0,613.0
4,5,built-up,"POLYGON ((628624.995 6554811.988, 628625.32 65...",4,257.0,149.0

### Export zonal statistics results
Save the polygon-level zonal statistics to GeoPackage and CSV.

In [22]:
# save polygons with zonal stats as geopackage or csv

polygons_out.to_file("polygons_output.gpkg", driver="GPKG")
polygons_out.to_csv("polygons_output.csv", index=False)