In [1]:
import pandas as pd

In [2]:
proj_dir = "Z:/landscape_geoinfo/datacube"
source = "sentinel2"
fp = (
    f"{proj_dir}/working/nodata_stats/{source}/"
    f"nodata_calc_combined_{source}.csv"
)
df = pd.read_csv(fp)

In [3]:
df

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
0,sentinel2,2017,spring,2017-04-01_2017-05-31,bsi,957180000,506049580,1969004,955210996,0.434563
1,sentinel2,2017,summer,2017-06-01_2017-08-31,bsi,957180000,504099892,19316,957160684,0.004263
2,sentinel2,2017,autumn,2017-09-01_2017-10-31,bsi,957180000,546904984,42824408,914355592,9.451437
3,sentinel2,2017,spring,2017-04-01_2017-05-31,evi,957180000,506049580,1969004,955210996,0.434563
4,sentinel2,2017,summer,2017-06-01_2017-08-31,evi,957180000,504099892,19316,957160684,0.004263
...,...,...,...,...,...,...,...,...,...,...
238,sentinel2,2025,summer,2025-06-01_2025-08-31,ndwi,957180000,504080576,0,957180000,0.000000
239,sentinel2,2025,autumn,2025-09-01_2025-10-31,ndwi,957180000,504080576,0,957180000,0.000000
240,sentinel2,2025,spring,2025-04-01_2025-05-31,savi,957180000,504080576,0,957180000,0.000000
241,sentinel2,2025,summer,2025-06-01_2025-08-31,savi,957180000,504080576,0,957180000,0.000000
242,sentinel2,2025,autumn,2025-09-01_2025-10-31,savi,957180000,504080576,0,957180000,0.000000

In [4]:
# Describe index statistics across the full period
index_stats_full = (
    df.groupby("index")["percent_nodata"]
    .describe()
    .reset_index()
)

In [5]:
index_stats_full

   index  count      mean       std  min  25%  50%       75%       max
0    bsi   27.0  0.370789  1.816747  0.0  0.0  0.0  0.000135  9.451437
1    evi   27.0  0.370786  1.816730  0.0  0.0  0.0  0.000135  9.451353
2    fvc   27.0  0.370786  1.816730  0.0  0.0  0.0  0.000135  9.451353
3  gndvi   27.0  0.370786  1.816730  0.0  0.0  0.0  0.000135  9.451353
4    lai   27.0  0.370786  1.816730  0.0  0.0  0.0  0.000135  9.451353
5   ndmi   27.0  0.370789  1.816747  0.0  0.0  0.0  0.000135  9.451437
6   ndvi   27.0  0.380002  1.864567  0.0  0.0  0.0  0.000135  9.700180
7   ndwi   27.0  0.370786  1.816730  0.0  0.0  0.0  0.000135  9.451353
8   savi   27.0  0.370786  1.816730  0.0  0.0  0.0  0.000135  9.451353

In [6]:
index_stats_full.to_csv(
    (
        f"{proj_dir}/working/nodata_stats/"
        f"nodata_index_stats_full_{source}.csv"
    ),
    index=False
)

In [7]:
# Describe index statistics across seasons
index_stats_seasons = (
    df.groupby(["index", "season"])["percent_nodata"]
    .describe()
    .reset_index()
)

In [8]:
index_stats_seasons

,index,season,count,mean,std,min,25%,50%,75%,max
0,bsi,autumn,9.0,1.063586,3.145573,0.0,0.0,0.000061,0.036197,9.451437
1,bsi,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
2,bsi,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
3,evi,autumn,9.0,1.063577,3.145545,0.0,0.0,0.000061,0.036197,9.451353
4,evi,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
5,evi,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
6,fvc,autumn,9.0,1.063576,3.145545,0.0,0.0,0.000061,0.036197,9.451353
7,fvc,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
8,fvc,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
9,gndvi,autumn,9.0,1.063576,3.145545,0.0,0.0,0.000061,0.036197,9.451353
10,gndvi,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
11,gndvi,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
12,lai,autumn,9.0,1.063577,3.145545,0.0,0.0,0.000061,0.036197,9.451353
13,lai,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
14,lai,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
15,ndmi,autumn,9.0,1.063586,3.145574,0.0,0.0,0.000061,0.036197,9.451437
16,ndmi,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
17,ndmi,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
18,ndvi,autumn,9.0,1.091224,3.228484,0.0,0.0,0.000061,0.036197,9.700180
19,ndvi,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
20,ndvi,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
21,ndwi,autumn,9.0,1.063576,3.145545,0.0,0.0,0.000061,0.036197,9.451353
22,ndwi,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
23,ndwi,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263
24,savi,autumn,9.0,1.063576,3.145545,0.0,0.0,0.000061,0.036197,9.451353
25,savi,spring,9.0,0.048285,0.144854,0.0,0.0,0.000000,0.000000,0.434563
26,savi,summer,9.0,0.000497,0.001414,0.0,0.0,0.000000,0.000000,0.004263

In [9]:
index_stats_seasons.to_csv(
    (
        f"{proj_dir}/working/nodata_stats/"
        f"nodata_index_stats_seasons_{source}.csv"
    ),
    index=False
)

In [10]:
# Describe overall statistics across seasons
overall_stats_seasons = (
    df.groupby(["year", "season"])["percent_nodata"]
    .describe()
    .reset_index()
)

In [11]:
overall_stats_seasons

,year,season,count,mean,std,min,25%,50%,75%,max
0,2017,autumn,9.0,9.479019,0.082935,9.451353,9.451353,9.451353,9.451437,9.700180
1,2017,spring,9.0,0.434563,0.000000,0.434563,0.434563,0.434563,0.434563,0.434563
2,2017,summer,9.0,0.004263,0.000000,0.004263,0.004263,0.004263,0.004263,0.004263
3,2018,autumn,9.0,0.000786,0.000000,0.000786,0.000786,0.000786,0.000786,0.000786
4,2018,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,2018,summer,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,2019,autumn,9.0,0.083775,0.000000,0.083775,0.083775,0.083775,0.083775,0.083775
7,2019,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,2019,summer,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,2020,autumn,9.0,0.000061,0.000000,0.000061,0.000061,0.000061,0.000061,0.000061
10,2020,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,2020,summer,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,2021,autumn,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,2021,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,2021,summer,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,2022,autumn,9.0,0.000017,0.000002,0.000015,0.000015,0.000015,0.000020,0.000020
16,2022,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,2022,summer,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,2023,autumn,9.0,0.036197,0.000000,0.036197,0.036197,0.036197,0.036197,0.036197
19,2023,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,2023,summer,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,2024,autumn,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,2024,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,2024,summer,9.0,0.000210,0.000000,0.000210,0.000210,0.000210,0.000210,0.000210
24,2025,autumn,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,2025,spring,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,2025,summer,9.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [12]:
overall_stats_seasons.to_csv(
    (
        f"{proj_dir}/working/nodata_stats/"
        f"nodata_overall_stats_seasons_{source}.csv"
    ),
    index=False
)

In [13]:
for index in df["index"].unique():
    max_missing = (
        df[df["index"] == index]
        .sort_values("percent_nodata", ascending=False)
        .head()
    )
    display(max_missing)

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
2,sentinel2,2017,autumn,2017-09-01_2017-10-31,bsi,957180000,546904984,42824408,914355592,9.451437
0,sentinel2,2017,spring,2017-04-01_2017-05-31,bsi,957180000,506049580,1969004,955210996,0.434563
56,sentinel2,2019,autumn,2019-09-01_2019-10-31,bsi,957180000,504460159,379583,956800417,0.083775
164,sentinel2,2023,autumn,2023-09-01_2023-10-31,bsi,957180000,504244584,164008,957015992,0.036197
1,sentinel2,2017,summer,2017-06-01_2017-08-31,bsi,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
5,sentinel2,2017,autumn,2017-09-01_2017-10-31,evi,957180000,546904601,42824025,914355975,9.451353
3,sentinel2,2017,spring,2017-04-01_2017-05-31,evi,957180000,506049580,1969004,955210996,0.434563
59,sentinel2,2019,autumn,2019-09-01_2019-10-31,evi,957180000,504460159,379583,956800417,0.083775
167,sentinel2,2023,autumn,2023-09-01_2023-10-31,evi,957180000,504244584,164008,957015992,0.036197
4,sentinel2,2017,summer,2017-06-01_2017-08-31,evi,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
8,sentinel2,2017,autumn,2017-09-01_2017-10-31,fvc,957180000,546904601,42824025,914355975,9.451353
6,sentinel2,2017,spring,2017-04-01_2017-05-31,fvc,957180000,506049580,1969004,955210996,0.434563
62,sentinel2,2019,autumn,2019-09-01_2019-10-31,fvc,957180000,504460159,379583,956800417,0.083775
170,sentinel2,2023,autumn,2023-09-01_2023-10-31,fvc,957180000,504244584,164008,957015992,0.036197
7,sentinel2,2017,summer,2017-06-01_2017-08-31,fvc,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
11,sentinel2,2017,autumn,2017-09-01_2017-10-31,gndvi,957180000,546904601,42824025,914355975,9.451353
9,sentinel2,2017,spring,2017-04-01_2017-05-31,gndvi,957180000,506049580,1969004,955210996,0.434563
65,sentinel2,2019,autumn,2019-09-01_2019-10-31,gndvi,957180000,504460159,379583,956800417,0.083775
173,sentinel2,2023,autumn,2023-09-01_2023-10-31,gndvi,957180000,504244584,164008,957015992,0.036197
10,sentinel2,2017,summer,2017-06-01_2017-08-31,gndvi,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
14,sentinel2,2017,autumn,2017-09-01_2017-10-31,lai,957180000,546904601,42824025,914355975,9.451353
12,sentinel2,2017,spring,2017-04-01_2017-05-31,lai,957180000,506049580,1969004,955210996,0.434563
68,sentinel2,2019,autumn,2019-09-01_2019-10-31,lai,957180000,504460159,379583,956800417,0.083775
176,sentinel2,2023,autumn,2023-09-01_2023-10-31,lai,957180000,504244584,164008,957015992,0.036197
13,sentinel2,2017,summer,2017-06-01_2017-08-31,lai,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
17,sentinel2,2017,autumn,2017-09-01_2017-10-31,ndmi,957180000,546904984,42824408,914355592,9.451437
15,sentinel2,2017,spring,2017-04-01_2017-05-31,ndmi,957180000,506049580,1969004,955210996,0.434563
71,sentinel2,2019,autumn,2019-09-01_2019-10-31,ndmi,957180000,504460159,379583,956800417,0.083775
179,sentinel2,2023,autumn,2023-09-01_2023-10-31,ndmi,957180000,504244584,164008,957015992,0.036197
16,sentinel2,2017,summer,2017-06-01_2017-08-31,ndmi,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
20,sentinel2,2017,autumn,2017-09-01_2017-10-31,ndvi,957180000,548032034,43951458,913228542,9.700180
18,sentinel2,2017,spring,2017-04-01_2017-05-31,ndvi,957180000,506049580,1969004,955210996,0.434563
74,sentinel2,2019,autumn,2019-09-01_2019-10-31,ndvi,957180000,504460159,379583,956800417,0.083775
182,sentinel2,2023,autumn,2023-09-01_2023-10-31,ndvi,957180000,504244584,164008,957015992,0.036197
19,sentinel2,2017,summer,2017-06-01_2017-08-31,ndvi,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
23,sentinel2,2017,autumn,2017-09-01_2017-10-31,ndwi,957180000,546904601,42824025,914355975,9.451353
21,sentinel2,2017,spring,2017-04-01_2017-05-31,ndwi,957180000,506049580,1969004,955210996,0.434563
77,sentinel2,2019,autumn,2019-09-01_2019-10-31,ndwi,957180000,504460159,379583,956800417,0.083775
185,sentinel2,2023,autumn,2023-09-01_2023-10-31,ndwi,957180000,504244584,164008,957015992,0.036197
22,sentinel2,2017,summer,2017-06-01_2017-08-31,ndwi,957180000,504099892,19316,957160684,0.004263

,source,year,season,season_str,index,total_pixels,nodata_pixels,true_nodata_pixels,valid_pixels,percent_nodata
26,sentinel2,2017,autumn,2017-09-01_2017-10-31,savi,957180000,546904601,42824025,914355975,9.451353
24,sentinel2,2017,spring,2017-04-01_2017-05-31,savi,957180000,506049580,1969004,955210996,0.434563
80,sentinel2,2019,autumn,2019-09-01_2019-10-31,savi,957180000,504460159,379583,956800417,0.083775
188,sentinel2,2023,autumn,2023-09-01_2023-10-31,savi,957180000,504244584,164008,957015992,0.036197
25,sentinel2,2017,summer,2017-06-01_2017-08-31,savi,957180000,504099892,19316,957160684,0.004263